<a href="https://colab.research.google.com/github/adakar2000/UczenieMaszynowe/blob/UseCase1/UM_us1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('/content/creditcard.csv', sep=",", index_col=[0]).reset_index(drop=True)
df = df.dropna()

In [16]:
X, y = df.drop(['Class', 'V22'], axis =1), df[['Class']]

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


In [30]:
X, y = df.drop('Class', axis =1), df[['Class']]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [32]:
print(X)


              V1        V2        V3        V4        V5        V6        V7  \
0      -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1       1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2      -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3      -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4      -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
...          ...       ...       ...       ...       ...       ...       ...   
223852  2.032448 -0.022721 -1.429822  0.132413  0.351459 -0.541265  0.121327   
223853 -0.841297  0.826026  0.653840  0.081422  0.944247 -0.946773  1.359069   
223854  1.961248 -0.047037 -1.924226  0.403639  0.226717 -1.054853  0.125899   
223855 -0.995266  0.689360 -0.129920 -1.019210 -0.004685 -0.737544  1.442358   
223856  2.072290 -0.059782 -1.128102  0.382643 -0.078541 -1.131168  0.177014   

              V8        V9       V10  .

In [33]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
confusion_matrix(y_test, y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Accuracy: 0.9991065844724382
Precision: 0.9302325581395349
Recall: 0.5970149253731343


array([[67018,     6],
       [   54,    80]])

In [36]:
from imblearn.over_sampling import SMOTE
from collections import Counter
oversample = SMOTE()
X_train_os, y_train_os = oversample.fit_resample(X_train, y_train)
counter = Counter(y)

In [40]:
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

In [41]:
from imblearn .under_sampling import EditedNearestNeighbours
pca = PCA(n_components=2)
enn = EditedNearestNeighbours()
smote = SMOTE (random_state=0)
knn = KNeighborsClassifier(n_neighbors=1)

In [47]:
from imblearn.pipeline import make_pipeline
model = make_pipeline(pca, enn, smote, knn)
over = SMOTE(sampling_strategy=0.1)
under = RandomUnderSampler(sampling_strategy=0.5)
steps = [('over', over), ('under', under), ('model', model)]
pipeline = make_pipeline(over,under,model)

In [52]:
from sklearn.metrics import classification_report
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


              precision    recall  f1-score   support

         0.0       1.00      0.95      0.98     67024
         1.0       0.04      0.84      0.07       134

    accuracy                           0.95     67158
   macro avg       0.52      0.90      0.52     67158
weighted avg       1.00      0.95      0.97     67158



In [55]:
from sklearn.linear_model import LogisticRegression

In [59]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
y_pred = lr.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
confusion_matrix(y_test, y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.9988981208493404
Precision: 0.8571428571428571
Recall: 0.5373134328358209


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[67012,    12],
       [   62,    72]])

Z wagami


In [62]:
weights = {0:1.0, 1:1.0}
lr = LogisticRegression(solver='lbfgs', class_weight=weights)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
y_pred = lr.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
confusion_matrix(y_test, y_pred)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy: 0.9988981208493404
Precision: 0.8571428571428571
Recall: 0.5373134328358209


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[67012,    12],
       [   62,    72]])